# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# IM - I have took the standard ruby GitHub Actions workflow, removed the on push to main, 
# and replaced it with a scheduled Sunday at 15:00 CEST call. Cron from ChatGPT. 
# TODO - Add the type of call to helloworld.rb

name: Ruby Availability Tweet

on:
  schedule:
  - cron: "0 13 * * 0"

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run helloworld.rb to tweet availability
      run: bundle exec ruby helloworld.rb false, "availability_tweet", ${{ vars.TWITTER_API_KEY }}
